### ISSUE TITLE
some questions about baseline

### ISSUE THREAD

**Issue by jaytsien** [dmis-lab/excord#1]
Hello, I reproduce the experiment in your paper and found that the roberta base only has an F1 value of 65.8. It is much lower than the 66.5 reported in the paper. Can you provide the parameters of the baseline?

**Comment by gangwook** [comment]
Hi, jaytsien

Here is our roberta-base model you requested. 
[Drive Folder](https://drive.google.com/drive/folders/1QefvHCHbASD2md3roKL85ysymhvsNIXQ?usp=sharing)
I checked it achieves an F1 value of 66.45 as we reported.

Also, please note that we use the `--fp16` argument for all experiments

Thanks!

**Comment by zorikg** [comment]
Hi Gangwoo Kim,
Can you please share the exact parameter for `run_quac.py` script for training the **RoBERTa end-to-end** baseline **without EXCORD**?
Thanks!
